test-unit/test-unit

lib/test/unit/testcase.rb

I fixed typos that is part of #100

Fix typos in comments

---

lib/test/unit/assertions.rb

I fixed a typo that is part of #100

Fix a typo in YARD

---

TODO

It seems that TODO file is not used.

Delete TODO file

---

sample/adder.rb
sample/subtracter.rb
sample/test_adder.rb
sample/test_subtracter.rb

Update sample code

---

doc/text/news.md

I'm sure #123 wasn't sent by Mr. SEATO.

Typo in a person's name

---

doc/text/getting-started.md

I made Getting started page for `test-unit`. 
Please review this documents.

Add getting started document

---

doc/po/ja.po
doc/text/getting-started.md

Localize getting-started document in Japanese.

---

lib/test/unit/collector/load.rb

recreated #153 with correct commit logs

Report require failed omissions as error

---

lib/test/unit/autorunner.rb

Closes #155 Typographical error of attribute ":stop_on_failure"

---

README.md

This PR changes the build badges to SVG for sharper readability ✨

README: SVG badge icons

---

test-unit.gemspec

In my understanding, including `test_files` in gemspec is needless now
* https://github.com/rubygems/guides/issues/90
* https://github.com/rubygems/bundler/pull/3207
* https://pocke.hatenablog.com/entry/2020/10/24/171955 (ja)
I personally use below rake task in own gems to check the packing results.
```ruby
desc 'Prevent miss packaging!'
task :view_packaging_files do
sh 'rm -rf ./pkg'
sh 'rake build'
cd 'pkg' do
sh 'gem unpack *.gem'
sh 'tree -I *\.gem'
end
sh 'rm -rf ./pkg'
end
```
Before this change
---
```plaintext
.
└── test-unit-3.4.5
├── BSDL
├── COPYING
├── PSFL
├── README.md
├── Rakefile
├── doc
│   └── text
│       ├── getting-started.md
│       ├── how-to.md
│       └── news.md
├── lib
│   ├── test
│   │   ├── unit
│   │   │   ├── assertion-failed-error.rb
│   │   │   ├── …
```

Do not contain needless `test_files` in gem package

---

doc/po/ja.po
lib/test/unit.rb

Fix a typo s/Regsiter/Register/

---

doc/po/ja.po
lib/test/unit/testsuite.rb

Fix a typo s/Retuns/Returns/

---

README.md

Fix a typo `s/compatiblity/compatibility/`

---

doc/po/ja.po
doc/text/getting-started.md

Fix a typo `s/inforomation/information/`

---

lib/test/unit/assertions.rb

My motivation is avoiding confusion as #182 🙏

Clarify `assert_nil` behavior in description

---

README.md

I think this is helpful information to add.

Clarify that test-unit ships with Ruby

---

README.md

Since Ruby ships with two testing frameworks, I think it's important to give some guidance about which to choose, e.g.
* Is `test-unit` a viable choice for new projects, or it just for legacy projects? 
* Is `test-unit` opinionated in ways that differ from minitest?
The description here is incomplete because I don't know the answers, but I'd like to find out.

Add minitest comparison notes?

---

lib/test/unit/testcase.rb

The comment was a little too hopeful 😄

doc: update when multi Ractor mode will be improved

---

lib/test/unit/testsuite.rb

testsuite: Extract run_tests method

---

lib/test/unit/assertions.rb

``Array#count`` is simpler than ``Array#find_all`` + ``Array#size``.

Prefer count in Template new

---

lib/test/unit/autorunner.rb
lib/test/unit/test-suite-runner.rb
lib/test/unit/testcase.rb
lib/test/unit/testsuite.rb
lib/test/unit/ui/testrunner.rb
lib/test/unit/ui/testrunnermediator.rb

Replacing default implementation, because it does not make sense.

Introduce backend switching in AutoRunner

---

lib/test/unit/test-suite-runner.rb
lib/test/unit/testcase.rb
lib/test/unit/testsuite.rb
lib/test/unit/ui/testrunnermediator.rb

GitHub: GH-235
It does not change internal logic at all.

Use meaningful name

---

lib/test/unit/sub-test-result.rb

GitHub: fix GH-271
Reported by Takahiro Ueda. Thanks!!!

thread runner: add missing test result support

---

lib/test/unit/testcase.rb

GitHub: GH-235
To allow tests to access the runner class via `TestCase#runner_class`.

Introduce #runner_class to TestCase

---

lib/test/unit/test-suite-thread-runner.rb

GitHub: GH-235 GH-285
This patch will execute the expected order in the thread runner.
Expected execution order:
First, all parallel unsafe tests are executed. Next, all parallel safe tests are executed.
1. All parallel unsafe tests
2. All parallel safe tests
Actual execution order:
Parallel unsafe and parallel safe tests are executed in mixed order.
1. parallel unsafe tests
2. parallel safe tests
3. parallel safe tests
4. parallel unsafe tests
5. ...

thread runner: make tests truly parallel-safe

---

bin/test-unit

GitHub: fix GH-288
This patch is the final step. It allows specifying test targets.

bin: add support for specifying test targets

---

README.md

doc: use https instead of http

---

lib/test/unit/testcase.rb
test/collector/test-descendant.rb

doc: test: add `ractor def test_XXX` style

---

doc/text/news.md

Add 3.6.9 entry
