test-unit.gemspec
cannot find link to http://test-unit.github.io/ in RubyGems.org page :worried:
=> fix a link Homepage in https://rubygems.org/gems/test-unit

appveyor.yml
The reason for this change is that --no-rdoc and --no-ri option is deprecated.
* [gem install(command reference)](http://guides.rubygems.org/command-reference/#gem-install)
* [gemrcの--no-riと--no-rdoc、deprecatedなoptionなのでみなおしたほうがいいかもですよ](http://qiita.com/kei_q/items/d13235157fcfc435489d)
=> Use --no-document option instead of --no-rdoc and --no-ri option

.travis.yml
If you execute `travis lint` command, the following warnings is displayed.
Warnings for .travis.yml:
[x] value for notifications section is empty, dropping
[x] missing key language, defaulting to ruby
[x] in notifications section: unexpected key recipients, dropping
=> Fix the warnings from .travis.yml

lib/test/unit/code-snippet-fetcher.rb
If Encoding.default_internal is set, only external encoding set
cause encoding conversion, which may fail.
=> set both external and internal encoding to prevent conversion

lib/test/unit/util/backtracefilter.rb, test/util/test_backtracefilter.rb
~~~
test_power_assert(T)
/usr/local/ruby-2.2/lib/ruby/gems/2.2.0/gems/power_assert-0.2.2/lib/power_assert.rb:29:in `start'
t.rb:5:in `test_power_assert'
2:
3: class T < Test::Unit::TestCase
4:   def test_power_assert
=> 5:     assert { "a".empty? }
6:   end
7: end
~~~
~~~
test_power_assert(T)
t.rb:5:in `test_power_assert'
2:
3: class T < Test::Unit::TestCase
4:   def test_power_assert
=> 5:     assert { "a".empty? }
6:   end
7: end
~~~
=> Filter backtrace of power_assert

lib/test/unit/util/backtracefilter.rb
test-unit-power_assert defines Test::Unit::PowerAssert.
So when test-unit-power_assert is required before test-unit,
`PowerAssert` in Test::Unit::Util::BacktraceFilter refers to
Test::Unit::PowerAssert and it causes a following error.
~~~
$ ruby -rtest/unit/power_assert -rtest/unit -eexit
.../test/unit/util/backtracefilter.rb:16:in `method': undefined method `start' for class `Module' (NameError)
~~~
=> Fix conflict with test-unit-power_assert

.travis.yml
Travis says it is faster than legacy infrastructure.
See for detail: https://docs.travis-ci.com/user/migrating-from-legacy/
=> Migrate to Travis' new container

lib/test/unit/testcase.rb
that has invalid codeblock and list.
Screenshot of current reference manual:
"Example" and "call order" are hard to read.
=> Fix Testcase class document

test/test-assertions.rb
In power_assert 1.0.0, assertion message is improved.
This PR follows up to it.
~~~
1 == 2
1 == 2
|
false
~~~
=> Follow up to power_assert 1.0.0

lib/test/unit/attribute.rb, lib/test/unit/testcase.rb
Context: #142
----------
I just noticed following behavior when I tried to write documentation:
```ruby
require 'test-unit'
class AttrTest < Test::Unit::TestCase
def test_slow_method1
p self[:speed] # => :slow
end
attribute :speed, :slow, {keep: true}, :test_slow_method1
def test_slow_method2
p self[:speed] # => nil
end
end
```
Is this intentional?
=> doc: Add `attribute` document

README.md
http://test-unit.github.io/test-unit/en/index.html  
`How To (link for GitHub)` link is relative path.
```
<a href="doc/text/how-to.md">How To</a>
```
=> Fix missing link in doc/reference

lib/test/unit/testcase.rb
Steps to reproduce:
```
% cat test.rb
require 'test/unit'
class TestFoo < Test::Unit::TestCase
sub_test_case 'a' do
data('x' => 1)
test 'foo' do |x|
end
end
sub_test_case 'b' do
data('x' => 1)
test 'foo' do
end
end
end
$ ruby test.rb
Loaded suite test
Started
.N
==============================================================================================================================================================
#<Class:0x007fd40f226da8>#test: foo misses a parameter to take test data [test: foo[x](TestFoo::b)]
/Users/yito/ruby/test-unit/test.rb:6
==============================================================================================================================================================
.
Finished in 0.001603 seconds. …
```
=> Data driven tests with duplicated name break a location in a notification message for missing a parameter

test-unit.gemspec
Makes it easy to programatically find the source code and changelog for `test-unit`, using the rubygems API. More details on the direction of travel for gemspecs is [here](https://github.com/rubygems/rubygems.org/issues/1127) and [here](https://github.com/rubygems/rubygems.org/pull/1234), and the current state is [here](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb).
(My interest in this is so that [Dependabot](https://dependabot.com) can find a link to the `test-unit` source code when it creates PRs. Without that link, we generate PRs like [this one](https://github.com/greysteil/onebody/pull/20), rather than PRs like [this one](https://github.com/greysteil/onebody/pull/12).)
=> Add source code link to gemspec

doc/po/ja.po, lib/test/unit.rb, lib/test/unit/assertions.rb, lib/test/unit/data.rb, lib/test/unit/notification.rb, lib/test/unit/omission.rb, lib/test/unit/pending.rb, lib/test/unit/testcase.rb, lib/test/unit/util/observable.rb, lib/test/unit/util/output.rb
see #163 
This PR makes following changes. These should improve the look of the reference manual.
* Change markup format of source codes from RDoc to Markdown.
* Convert "heading level 1": `=` --> `#`
* Convert "heading level 2": `==` --> `##`
* Convert "code": `+WORD+` --> <code>\`WORD\`</code>
* Convert "definition lists".
* However, "Author", "Copyright" and "License" at the beginning of the source code have not changed.
* Change indents of "code block".
* Insert necessary blank lines.
* Change `ja.po`
=> Convert markup format of source codes from RDoc to Markdown

lib/test/unit/code-snippet-fetcher.rb
Retry https://github.com/test-unit/test-unit/commit/5929a43ee3969b96017f84047487c6ce5cbe05ae
A test fails in my env without this patch (e.g https://github.com/ganmacs/fluent-test-ci/runs/380973150)
=> Fix encoding related error on showing code snippet

lib/test/unit.rb
Hello, I found a broken link in the docs. Hope this helps!
I also noticed that this affects a derived file at [`doc/po/ja.po`](https://github.com/test-unit/test-unit/blob/4c0c704334e0243d80555dc4075a15985012496c/doc/po/ja.po#L2405-L2413) which is checked into the source tree instead of being ignored like most of the other generated docs. I did not update this file because it looks like there are several pending updates, but I can update it for this change if desired.
Thank you!
=> Docs: update link to ruby-talk mailing list

README.md
Currently test/unit does NOT adopt the same licence as new Ruby's. It uses the old Ruby's.
Ref. https://github.com/test-unit/test-unit/issues/172
=> doc: specify licence explicitly

lib/test/unit/autorunner.rb
Fix duplication of type conversions.
https://github.com/test-unit/test-unit/blob/1516068ffcc1455029c21d77166acc5306b105ce/lib/test/unit/autorunner.rb#L461-L466
=> key has already symbol

lib/test/unit/color-scheme.rb, lib/test/unit/ui/console/testrunner.rb, test/test-color-scheme.rb
Adds better color support detection based on TERM variable.  Ultimately,
it would probably be better if we could delegate to the terminfo DB for
this.  But relying on "color" or "256color" or "direct" is fairly safe.
=> Improve TERM color detection support

lib/test/unit/assertions.rb, test/test-assertions.rb
This makes the behaviour friendlier, and also consistent with
`assert_match`.
=> Allow strings in `assert_not_match`

test/test-assertions.rb
This looks added in 8f156ded038e96e4b63e2d4bc7d7c10d57562823
Looks having some issues.
* Named the prefix `tset_`, it is not running in `bundle exec rake`.
* The test case is not correct or outdated, I think.
* It is actually testing `assert_respond_to`  instead of `assert_not_respond_to `
=> Fix tests around `assert_not_respond_to` assertion

lib/test/unit/assertions.rb, test/test-assertions.rb
Hi!, I know this PR makes breaking change of the assertions!
Now `assert_equal(true, something)` and `assert_true(something)` does not make same result.
https://github.com/test-unit/test-unit/blob/7dd387ef811e35e7b53d5200fe89ccea1e070e73/lib/test/unit/assertions.rb#L244
Is this an intentional behavior?
Considering the use-case, I would like to ensure matching `true` and `false`, even if the `actual` having evil `==`.
How do you think? :pray:
=> Boolean assertions checks `true` and `false` without `actual` definitions

test-unit.gemspec
test-unit looks positive to writing signature with YARD.
So how about to reference the URL in https://rubygems.org/gems/test-unit?
Before
---
After
---
If you negative to depend https://rubydoc.info, I will try another PR as self-hosting YARD with `gh-pages`. Then please tell me!
=> Add `documentation_uri` and `bug_tracker_uri` in gemspec

.github/workflows/test.yml
https://github.com/actions/checkout/compare/master..main
https://github.com/actions/checkout/compare/master..v2
Looks `master` branch is not maintained, I’m guessing they have changed default branch to `main` from `master`.
=> Update using GitHub Actions branch name

.github/dependabot.yml
I personally use dependabot config as below in own gems.
```yaml
version: 2
updates:
- package-ecosystem: "github-actions"
directory: "/"
schedule:
interval: "daily"
time: "08:00"
timezone: "Asia/Tokyo"
- package-ecosystem: "bundler"
directory: "/"
schedule:
interval: "daily"
time: "08:00"
timezone: "Asia/Tokyo"
versioning-strategy: increase
```
test-unit does not specify versions of dependencies, so `bundler` config is needless, I think.
But introducing `github-actions` might prevent similar as #187 (Honestly, I don't have confident for the behavior 🙇 )
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem
How do you think?
=> Introduce dependabot to update GitHub Actions

lib/test/unit/assertions.rb
Is this correct understanding? https://github.com/test-unit/test-unit/blob/a2106658fe85e79478322e03a33f75977b82c911/lib/test/unit/assertions.rb#L54
The new description is taken from `assert`.
https://github.com/test-unit/test-unit/blob/a2106658fe85e79478322e03a33f75977b82c911/lib/test/unit/assertions.rb#L91
=> Fix description for `assert_block`, it is considering `truthy` not `true`

lib/test/unit/assertions.rb
=> Use YARD tag `@deprecated` for `assert_no_match`

lib/test/unit.rb
Before
---
After
---
The link will work
=> Use `@deprecated` tag with reference syntax

README.md
Current badges looks bit old 📛 
* Missing GitHub Actions badge. It is preferable rather than Travis-CI because testing on newer rubies.
* https://travis-ci.org/test-unit/test-unit shows old results, they looks have been moved to new URL.
Before
---
After
---
Note
---
`doc/po/ja.po` looks having same URL, but I did not update in this PR
=> Update status badges on README

lib/test/unit/assertions.rb
This PR just update example documents to follow a2106658fe85e79478322e03a33f75977b82c911
=> Prefer `assert_all` rather than `assert_all?` in examples

lib/test/unit/assertions.rb
The motivation is below 🙇 
* Clarify checking `truthy`, `falsy` instead of `true`, `false` as #191 
* Clarify using `__send__` not `send`
=> Accurate description of some assertions behaviors

lib/test/unit/testcase.rb
As `Mutex` has been moved under `Thread` since ruby 2.3, and might be deprecated in future.
=> Prefer canonical qualified names for classes under Thread

lib/test/unit/assertion-failed-error.rb
Follow https://github.com/test-unit/test-unit/commit/a66061f9236ae16eb8c287cf62bf60dc8d39ae45
Before Ruby 3.0, uninitialized instance variable shows warning as below.
Before
---
```console
$ ruby -v && bundle exec rake 2>&1 | grep 'warning' | fgrep '/lib/' | wc -l
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
175
```
After
---
```console
$ ruby -v && bundle exec rake 2>&1 | grep 'warning' | fgrep '/lib/' | wc -l
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
0
```
=> Fix to set class instance variable `@debug_on_failure`

lib/test/unit/priority.rb
This is a PR to check CI and to ask whether this require is needed.
In https://github.com/test-unit/test-unit/commit/135f2bfed57c1b30acc3350ef07cc8a0c04bdb6f, these require was moved to the `Test::Unit::Priority.enable` method, because users that don't use this class don't need to use it.
However, in https://github.com/test-unit/test-unit/commit/1eccf3cda5417ccb10047bd69f796eac9bf7c31c it was added back, although I'm not fully sure why.
I open this because requiring `fileutils` is causing some conflicts when testing the `etc` gem (because the `fileutils` version on older rubies used to require `etc`, and that causes conflicts with the `etc` version being tested). See https://github.com/ruby/etc/pull/14.
=> Restore lazy fileutils require

lib/test/unit/testcase.rb
I'm tackling a super trivial bug that happens when defining triple nested `sub_test_case` under `ActionView::TestCase` on Rails 6.1+, and for addressing that bug on test-unit-rails, we need to extract a method that defines `sub_test_case`'s class in this repo first.
I'll post another patch with more detailed description on test-unit-rails soon.
=> Extract sub_test_case class generation to a dedicated method

test/test-assertions.rb
Ref: https://bugs.ruby-lang.org/issues/18576
Ref: https://github.com/ruby/ruby/pull/5571
I'd like to rename `ASCII-8BIT` into `BINARY` for Ruby 3.2, and since test-unit's test suite is integrated into Ruby it breaks the build.
=> Update the test suite to handle ASCII-8BIT renaming.

Gemfile, lib/test/unit/assertions.rb, test-unit.gemspec, test/test-assertions.rb, test/testunit-test-util.rb
This accepts `BigDecimal` as input without converting `Float` implicitly for `assert_in_delta` and its family.
=> Support BigDecimal in assert_in_delta and its family

lib/test/unit/attribute.rb
Found in [ruby 2.7](https://github.com/kachick/ruby-gem-template/actions/runs/3179027537/jobs/5181100027), it makes warnings `warning: instance variable @cached_parent_test not initialized`
Looks related to 3058e8ac0c05a4851da4ce27830df3947f2618e8
=> Fix ivar name

README.md
https://github.com/seattlerb/minitest repo URL is changed to https://github.com/minitest/minitest. This update avoids unnecessary redirects from the old URL to the new URL.
=> [Doc] Update GitHub organization of minitest

lib/test/unit/collector/load.rb
Test::Unit::Collector::Load#collect takes a long time when there are a large number of test files.
This PR aims to reduce the execution time."
Reproduce code(`t.rb`):
```ruby
require 'test/unit'
require 'tmpdir'
ARGV.shift
files, tests = ARGV.shift(2).map(&:to_i)
Dir.mktmpdir do |dir|
files.times do |i|
File.write("#{dir}/#{i}_test.rb", <<~SCRIPT)
class Test#{i} < Test::Unit::TestCase
#{Array.new(tests) { |j| "  def test_#{j}; end" }.join("\n")}
end
SCRIPT
end
Test::Unit::AutoRunner.run(true, dir)
end
```
Benchmark:
```bash
ruby -r benchmark -e 'Benchmark.bmbm {|x| [[1000,10],[100,100],[10,1000]].each {|f,t| x.report("#{f},#{t}") { system "ruby -Ilib t.rb -- #{f} #{t} >/dev/null" } }}'
```
master
```
Rehearsal -------------------------------------------
1000,10   0.000037   0.000432 …
```
=> Reduce execution time for skipping duplicate test_cases

test-unit.gemspec
Because avoid unnecessary redirects.
=> doc: Use https instead of http

lib/test/unit/fault-location-detector.rb, test/test-test-case.rb, test/util/test_backtracefilter.rb
Ruby 3.4 will use a single quote instead of a backtrick as an open quote.
https://bugs.ruby-lang.org/issues/16495
Also, the backtrace line will have not only a method name but also its receiver class.
https://bugs.ruby-lang.org/issues/19117
=> Support Ruby 3.4's new error message format

lib/test/unit/testsuite.rb
Before:
`Array#shift` **removes** and returns leading elements. So, after removing, it's rolled up the number of tests to `@n_tests`.
After:
`Array#each` iterates over array elements, **without removing** them. Using `Array#each` instead of `Array#shift`, means there's no need to rolled up the number of tests to `@n_tests`.
=> testsuite: Remove unneeded instance variable

lib/test/unit/testsuite.rb
Use `Array#each` instead of `Array#shift` in GH-240.
Before GH-240 change:
`Array#shift` **removes** and returns leading elements. So after removing, it cached `TestCase#passed?` or `TestSuite#passed?` results to `@passed`.
After this change:
`Array#each` iterates over array elements, **without removing** them. Using `Array#each` instead of `Array#shift`, means there's no need to cached `TestCase#passed?` or `TestSuite#passed?` results to `@passed`.
Note:
Since `@passed = true` was set in `TestSuite#initialize`, it should default to true when there are no tests.
`Array#all?` returns true for an empty array below. The behavior remains unchanged, so there's no issue.
```ruby
[].all? { true }
```
=> testsuite: Remove unneeded cache

lib/test/unit/test-suite-runner.rb, lib/test/unit/testsuite.rb
Migrate the following methods from `TestSuite` to `TestSuiteRunner`.
- `#run`
- `#run_startup`
- `#run_tests`
- `#run_test`
- `#run_shutdown`
- `#handle_exception`
Then invoke `TestSuiteRunner` from `TestSuite`.
=> Abstract #run from TestSuite to TestSuiteRunner

lib/test/unit/util/observable.rb
In ``remove_listener``, ``Hash#delete`` already returns ``nil`` for missing keys.
In ``notify_listeners``, prefer ``Hash#each_value`` instead of ``Hash#values``.
=> Refactor Observable remove_listener and notify_listeners methods

lib/test/unit/test-suite-runner.rb, lib/test/unit/testsuite.rb
We want to switch the backend (`TestSuiteRunner`) with an option.
Currently, it operates sequentially, but we want to switch it to a `Thread` based or other parallel runner. `TestSuiteRunner` is hardcoded to invoke within `TestSuite#run`. It cannot be modified externally, so we need to implement a mechanism to enable external modification.
We guess two main approaches:
* Stop invoking the runner inside and instead accept it from the outside
* Allow injection of the runner from the outside
We considered the following approaches:
1. Pass the Runner as a `TestSuite#run` argument
Seems broken as the interface might change
```ruby
test.run(result) do |event_name, *args|
```
Here, `test` is a `TestCase` or `TestSuite` object. If it's
`TestCase`, use this argument. If it's `TestSuite`, use that …
=> Use TestSuiteRunner for a system global

lib/test/unit/test-suite-runner.rb
`TestSuite` only invokes `TestSuiteRunner.run` (not `.run` of parallel runners such as `Thread` base).
As a result, parallel runners don't need to store the default runner, so they use instance variables rather than class variables.
=> Make backend possible to switch globally

lib/test/unit/autorunner.rb
Add support for switching the backend such as `Thread`. Please note that
the `Thread` based runner is not yet available (raises `NameError`).
Examples:
* `ruby -I lib test/run-test.rb --parallel`: `Thread`
* `ruby -I lib test/run-test.rb --parallel=thread`: `Thread`
* `ruby -I lib test/run-test.rb --no-parallel`: Sequential
* `ruby -I lib test/run-test.rb` (no --parallel option): Sequential
Note:
We considered the following other options.
1. `--runner` option:
* Already exists but is used to switch the UI execution
* UI execution and internal parallelism are independent
* Seems does not make sense
2. `--executer` option
* Does not exist
* `TestSuiteRunner` has run methods (not execute)
* Seems does not make sense
=> Add --[no-]parallel option

lib/test/unit/autorunner.rb
Because others just have values in parentheses.
=> doc: align default value description

lib/test/unit/autorunner.rb, lib/test/unit/test-suite-runner.rb
Add switching the number of parallelism (the default value is the number of online processors in Ruby 2.2.0 or later, but fixed them to 1 for old Ruby). Please note that the `Thread` based runner is not yet available (raises `NameError`).
Note:
We considered the number of parallelism option names below:
1. `--n-threads`
* Backend is not just about `Thread`
* Seems does not make sense
2. `--jobs`
* We don't call this a job
* Seems does not make sense
3. `--n-workers`
* We already call this a worker
* Seems make sense
=> Add --n-workers option

lib/test/unit/runner/console.rb, lib/test/unit/ui/console/testrunner.rb
Add support for showing the top 5 slow tests in the summary output.
Please note that at this step, specifying the option will result is no change.
Refs GH-253.
=> Add --[no-]report-slow-tests option

test/test-fault-location-detector.rb
Because a class variable is scoped to the innermost enclosing class or module keywords. This scope does not include singleton class.
=> test fault-location-detector: use class instance vars to fix scope issue

lib/test/unit/ui/console/testrunner.rb
GitHub: GH-253
This is a part of adding support for showing the top 5 slow tests in the summary output.
This just collects the top 5 slow tests in descending order of test execution time, so it doesn't show in the summary output for now.
=> Collect the top 5 slow tests in descending order

lib/test/unit/ui/console/testrunner.rb
Because `TestCase#elapsed_time` can be used instead of `@test_start`. And `@test_start` is only used in the `--verbose` option, so it can be removed.
By the way, `TestCase#elapsed_time` is shorter than `Time.now - @test_start` (just a little). Because it excludes the execution time of operations like `TestResult#add_run`:
```lib/test/unit/testcase.rb
def run(result)
@internal_data.test_finished
result.add_run
yield(FINISHED, name)
yield(FINISHED_OBJECT, self)
end
```
=> ui console: remove a needless instance variable

lib/test/unit/ui/console/testrunner.rb
GitHub: GH-253
This is a part of adding support for showing the top 5 slow tests in the summary output.
This just show the top 5 slow tests with test name and execution time, so it doesn't show following infomation in the summary output for now.
- Test source location (easy to jump in editor)
- Command lines (easy to re-run)
=> Show the top 5 slow tests with test name and execution time

lib/test/unit/ui/console/testrunner.rb
GitHub: GH-253
This is a part of adding support for showing the top 5 slow tests in the summary output.
This just show the top 5 slow tests with test source location for easy to jump in the editor. So it doesn't show the following information in the summary output for now.
- Command lines (easy to re-run)
=> Show the top 5 slow tests with test source location

lib/test/unit/ui/console/testrunner.rb
GitHub: fix GH-253
This is a **final** part of adding support for showing the top 5 slow tests in the summary output.
This show the top 5 slow tests with `--location` option for easy to re-run command lines.
By the way, removing the `=` to make it easier to jump in the editor. Because including the `=` makes it difficult to jump in the editor:
```diff
-`--location=...` makes less sense than
+`--location ...`
^
```
=> Show the top 5 slow tests with --location option

lib/test/unit/assertions.rb, test/test-assertions.rb
It would be nice not to rely on `object_id`, which is not guaranteed to be available for `BasicObject` instances. This change uses `__id__` to require inspectees to have minimal methods.
=> Allow inspecting `BasicObject` instances without `object_id` method

lib/test/unit/autorunner.rb, lib/test/unit/sub-test-result.rb, lib/test/unit/test-suite-thread-runner.rb, lib/test/unit/test-thread-result.rb, lib/test/unit/testcase.rb, lib/test/unit/testresult.rb, lib/test/unit/testsuite.rb, test/collector/test-load.rb, test/test-data.rb, test/test-test-case.rb
Will be available `Thread` based runner when specifying `--parallel` or
`--parallel=thread` option.
Users can indicate whether the test is parallel safe by using
`Test::Unit::TestCase.parallel_safe?`. This method returns `true` by
default, indicating that the test is parallel safe.
=> Add support for parallelization with Thread backend

Rakefile, test/run-test.rb
GitHub: GH-235
Because allows specifying options like `--parallel` when running tests.
=> Make it possible to pass TESTOPTS

test/test-assertions.rb
GitHub: GH-235
Because each thread consumes memory independently when threads are run in parallel.
See also:
https://github.com/test-unit/test-unit/issues/235#issuecomment-2463192714
=> test: indicate parallel unsafe

lib/test/unit/test-run-context.rb, lib/test/unit/test-suite-runner.rb, lib/test/unit/test-suite-thread-runner.rb, lib/test/unit/test-thread-run-context.rb, lib/test/unit/testcase.rb, lib/test/unit/testsuite.rb, lib/test/unit/ui/testrunnermediator.rb, test/testunit-test-util.rb
GitHub: GH-272, GH-235
The current parallel implementation can't use `run_all_tests/run_tests` at the same time.
This patch will be easy to test and future extensibility.
=> Make TestSuite level testing

lib/test/unit/test-suite-thread-runner.rb, lib/test/unit/test-thread-run-context.rb
GitHub: GH-235
This patch will execute the expected order in the thread runner:
Expected execution order:
1. startup
2. run test
3. shutdown
Actual execution order:
1. startup
2. shutdown
3. run test
=> thread runner: fix shutdown execution order

test/test-data.rb
GitHub: GH-235, fix GH-283
Data driven tests sometimes fail when run in parallel based on Thread. Class variables are overwritten in the subclasses during setup/teardown, causing race conditions in a multithread environment.
We use startup/shutdown instead of setup/teardown, avoiding thread safety and preventing race conditions.
=> test data: avoid thread safety issue

test/collector/test-descendant.rb, test/collector/test-load.rb
Because `Test::Unit::Collector::Load#collect` is not a private method.
=> test: use `#collect` directly instead of `#send`

bin/test-unit, test-unit.gemspec
GitHub: GH-288
This patch is the first step. `test-unit` executable just invokes
`require "test/unit"; exit(Test::Unit::AutoRunner.run(true, "test"))`
and does not support specifying test targets yet.
=> Add support for command line tool

doc/po/ja.po, doc/text/how-to.md
GitHub: fix GH-293
Because the TAP runner has been extracted to
https://github.com/test-unit/test-unit-runner-tap
=> doc: use another built in runner

doc/text/getting-started.md
GitHub: GH-295
Since Bundler 2.2.0.rc.1, the `bundle gem` command has supported `-t test-unit`.
Localization document have not yet been updated.
=> doc: specify `test-unit` directly

lib/test/unit/autorunner.rb
GitHub: fix GH-300
Prefer `.test-unit` than `test-unit.yml` or `~/test-unit.yml`
=> Add support .test-unit for default options

lib/test/unit/testcase.rb, test/test-fixture.rb, test/test-test-case.rb
GitHub: GH-235
Since c26354f, instance variables add during test runs persisted longer than before. This patch ensures they are garbage collected at any time after each test run.
Reported by akira yamada. Thanks!!!
=> testcase: remove needless instance variables added during test runs

lib/test-unit.rb
GitHub: GH-311
This patch will reduce dependency on `$LOAD_PATH`.
More advanced replacements are out of scope for this patch, such as:
* Changes under `test/`
=> Use require_relative instead of autoload

lib/test/unit/autorunner.rb
Recently there have been some issues in Ruby head with binstubs. The following output is from https://github.com/ruby/ruby-dev-builder/actions/runs/15884945465/job/44794519509:
Like to add `test-unit` to the CLI test, and having a version option makes for a simple check.
```
Run ruby test_files/cli_test.rb
───── CLI Test ─────────────────
bundle    ✅   2.7.0.dev
gem       ✅   3.7.0.dev
irb       ✅   1.15.2
racc      ✅   1.8.1
rake      ✅   13.3.0
rbs       ❌   missing binstub
rdbg      ❌   missing binstub
rdoc      ✅   6.14.1
ruby 3.5.0dev (2025-06-25T17:13:11Z :detached: a1996b32a9) +PRISM [x86_64-linux]
bad exit
Error: Process completed with exit code 1.
```
=> Add `--version` cli option

test/test-assertions.rb, test/test-attribute-matcher.rb, test/test-code-snippet.rb, test/test-data.rb, test/test-fault-location-detector.rb, test/test-notification.rb, test/test-omission.rb, test/test-pending.rb
GitHub: fix GH-311
This is a follow-up to GH-312 and the final patch to fix GH-311.
This patch will reduce dependency on `$LOAD_PATH`.
It replaces `require` with `require_relative` for internal library files in `test/`.
If you want to run tests against the installed `test-unit`, you can still use the `test/` directory like this:
This example runs tests against the installed `test-unit` version 3.6.8.
```console
$ ruby -I $(gem env home)/gems/test-unit-3.6.8/lib bin/test-unit test
```
=> test: use require_relative instead of require

lib/test-unit.rb
This reverts commit 572b28afa0b387707dcb1229d2b96ba130f95f11.
GitHub: GH-320
We need to use another approach for it.
Reported by Mamoru TASAKA. Thanks!!!
=> Revert "Use require_relative instead of autoload (#313)"

lib/test-unit.rb
GitHub: fix GH-311
This patch will reduce dependency on `$LOAD_PATH`. Using `autoload` with an absolute path means it does not depend on `$LOAD_PATH`.
`Test::Unit::TestCase` and `Test::Unit::AutoRunner` are loaded using absolute paths before these constants are referred or redefined with the open class.
Suggested by nicholas a. evans. Thanks!!!
=> Use absolute path instead of relative path for autoload
